### ISSUE TITLE
actix-web hello-world performance

### ISSUE THREAD

**Issue by dacheng-gao** [dacheng-learn/rust#8]
Cargo.toml

```toml
[package]
name = "helloworld"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
```

main.rs

```rust
use actix_web::{get, web, App, HttpServer, Responder};

#[get("/hello/{name}")]
async fn greet(name: web::Path<String>) -> impl Responder {
    format!("Hello {}!", name)
}

#[actix_web::main] // or #[tokio::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new().service(greet)
    })
        .bind(("127.0.0.1", 5580))?
        .run()
        .await
}
```

<img width="422" alt="image" src="https://user-images.githubusercontent.com/13791720/174218942-a2fe8a2e-91c1-4ad7-8ca5-2e494adfbdfc.png">
